"""script originality

Revision ID: 13f56c8c5897
Revises: 72c60dd000df
Create Date: 2026-09-13 02:22:11.135139
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '13f56c8c5897'
down_revision = '72c60dd000df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originality', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_column('originality')

    # ### end Alembic commands ###
