"""publication visibility

Revision ID: 2f1b387fcdff
Revises: dd8bea133fba
Create Date: 2026-09-13 07:50:20.280910
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2f1b387fcdff'
down_revision = 'dd8bea133fba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('warning', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_column('warning')
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
