"""initial schema

Revision ID: 2fd06c8faaa9
Revises: 
Create Date: 2026-09-12 03:55:59.935399
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2fd06c8faaa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clip_assets')),
    sa.UniqueConstraint('path', name=op.f('uq_clip_assets_path'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('name', name=op.f('uq_projects_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('WARNING', 'ERROR', name='alertlevel'), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=200), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_alerts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by', sa.String(length=120), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('pdca_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('stage', sa.Enum('PLAN', 'DO', 'CHECK', 'ACT', name='pdcastage'), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('publication_ids', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=True),
    sa.Column('learnings', sa.Text(), nullable=True),
    sa.Column('next_actions', sa.JSON(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_pdca_cycles_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdca_cycles'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('template', sa.String(length=200), nullable=False),
    sa.Column('html_path', sa.String(length=600), nullable=True),
    sa.Column('pdf_path', sa.String(length=600), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', 'X', name='platform'), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_runs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_runs_keyword'), ['keyword'], unique=False)

    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', 'X', name='platform'), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=600), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_secret', sa.Text(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_social_accounts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_accounts')),
    sa.UniqueConstraint('project_id', 'platform', 'external_id', name='uq_account')
    )
    op.create_table('competitor_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', 'X', name='platform'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_competitor_posts_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_posts')),
    sa.UniqueConstraint('run_id', 'external_id', name='uq_run_external')
    )
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', 'X', name='platform'), nullable=False),
    sa.Column('target_duration_sec', sa.Float(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scripts_project_id_projects')),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_scripts_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts'))
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('base_script_id', sa.Integer(), nullable=True),
    sa.Column('winner_variant_id', sa.Integer(), nullable=True),
    sa.Column('conclusion', sa.JSON(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_script_id'], ['scripts.id'], name=op.f('fk_experiments_base_script_id_scripts')),
    sa.ForeignKeyConstraint(['cycle_id'], ['pdca_cycles.id'], name=op.f('fk_experiments_cycle_id_pdca_cycles')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_experiments_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_table('storyboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('style', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_storyboards_script_id_scripts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storyboards'))
    )
    op.create_table('structure_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('hook_type', sa.String(length=80), nullable=True),
    sa.Column('beats', sa.JSON(), nullable=False),
    sa.Column('telop', sa.JSON(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('takeaways', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['competitor_posts.id'], name=op.f('fk_structure_analyses_post_id_competitor_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structure_analyses')),
    sa.UniqueConstraint('post_id', name=op.f('uq_structure_analyses_post_id'))
    )
    op.create_table('renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('preset', sa.String(length=80), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], name=op.f('fk_renders_storyboard_id_storyboards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_renders'))
    )
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('telop', sa.Text(), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('camera', sa.String(length=200), nullable=True),
    sa.Column('transition', sa.String(length=80), nullable=True),
    sa.Column('image_path', sa.String(length=600), nullable=True),
    sa.Column('clip_path', sa.String(length=600), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], name=op.f('fk_shots_storyboard_id_storyboards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('treatment', sa.JSON(), nullable=False),
    sa.Column('publication_ids', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_variants_experiment_id_experiments')),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_variants_script_id_scripts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants'))
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('render_id', sa.Integer(), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', 'X', name='platform'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='publicationstatus'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('external_url', sa.String(length=600), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('claimed_by', sa.String(length=120), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], name=op.f('fk_publications_account_id_social_accounts')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_publications_project_id_projects')),
    sa.ForeignKeyConstraint(['render_id'], ['renders.id'], name=op.f('fk_publications_render_id_renders')),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_publications_script_id_scripts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications'))
    )
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('watch_time_sec', sa.Float(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_metric_snapshots_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_snapshots'))
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_captured_at'), ['captured_at'], unique=False)

    op.create_table('publish_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', 'X', name='platform'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], name=op.f('fk_publish_attempts_account_id_social_accounts')),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_publish_attempts_publication_id_publications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_attempts'))
    )
    with op.batch_alter_table('publish_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_attempts_attempted_at'), ['attempted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_attempts_attempted_at'))

    op.drop_table('publish_attempts')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_captured_at'))

    op.drop_table('metric_snapshots')
    op.drop_table('publications')
    op.drop_table('variants')
    op.drop_table('shots')
    op.drop_table('renders')
    op.drop_table('structure_analyses')
    op.drop_table('storyboards')
    op.drop_table('experiments')
    op.drop_table('scripts')
    op.drop_table('competitor_posts')
    op.drop_table('social_accounts')
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_runs_keyword'))

    op.drop_table('research_runs')
    op.drop_table('reports')
    op.drop_table('pdca_cycles')
    op.drop_table('jobs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_fingerprint'))

    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('clip_assets')
    # ### end Alembic commands ###
