"""retention metrics

Revision ID: 72c60dd000df
Revises: ba7cde0f0bae
Create Date: 2026-09-12 09:49:30.146852
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '72c60dd000df'
down_revision = 'ba7cde0f0bae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_watch_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('retention_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('skip_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reach', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('impressions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('click_through_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_column('click_through_rate')
        batch_op.drop_column('impressions')
        batch_op.drop_column('reach')
        batch_op.drop_column('skip_rate')
        batch_op.drop_column('retention_rate')
        batch_op.drop_column('avg_watch_sec')

    # ### end Alembic commands ###
