"""research telop, watched accounts, comments

Revision ID: ba7cde0f0bae
Revises: 2fd06c8faaa9
Create Date: 2026-09-12 05:46:41.235970
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ba7cde0f0bae'
down_revision = '2fd06c8faaa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', 'X', name='platform'), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_competitor_accounts_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_accounts')),
    sa.UniqueConstraint('project_id', 'platform', 'handle', name='uq_account_handle')
    )
    with op.batch_alter_table('competitor_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_accounts_handle'), ['handle'], unique=False)

    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['competitor_posts.id'], name=op.f('fk_post_comments_post_id_competitor_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_comments')),
    sa.UniqueConstraint('post_id', 'external_id', name='uq_comment_external')
    )
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_intent'), ['intent'], unique=False)

    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filters', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_research_runs_account_id_competitor_accounts'), 'competitor_accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_research_runs_account_id_competitor_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')
        batch_op.drop_column('filters')

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_intent'))

    op.drop_table('post_comments')
    with op.batch_alter_table('competitor_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_accounts_handle'))

    op.drop_table('competitor_accounts')
    # ### end Alembic commands ###
