"""script playbook

Revision ID: dd8bea133fba
Revises: e3da2c01056e
Create Date: 2026-09-13 04:24:08.691567
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'dd8bea133fba'
down_revision = 'e3da2c01056e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playbook', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_column('playbook')

    # ### end Alembic commands ###
