"""retention curve

Revision ID: e3da2c01056e
Revises: 13f56c8c5897
Create Date: 2026-09-13 02:40:44.950659
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e3da2c01056e'
down_revision = '13f56c8c5897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retention_curve', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_column('retention_curve')

    # ### end Alembic commands ###
